/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.ClienteController;
import banco.FuncionarioController;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import login.Login;
import usuario.cliente.Cliente;
import usuario.funcionario.Funcionario;
import usuario.Usuario;

/**
 *
 * @author jscal
 */
public class TelaLogin extends javax.swing.JFrame {
    //Login login;
    //public static ArrayList<Login> listaUsuario = new ArrayList<>();
    Usuario usuario;
    Funcionario funcAtual = null;
    Cliente clientAtual = null;
    FuncionarioController fc = new FuncionarioController();
    ClienteController cc = new ClienteController();
    public static ArrayList<Usuario> listaUsuario = new ArrayList<>();
    
    
    /**
     * Creates new form telaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsuario = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        inputUsuario = new javax.swing.JTextField();
        inputSenha = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelUENPflix = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        labelUsuario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelUsuario.setText("Usuario:");

        labelSenha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelSenha.setText("Senha:");

        inputSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSenhaActionPerformed(evt);
            }
        });
        inputSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login(evt);
            }
        });

        btLogin.setText("Logar");
        btLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLoginMouseClicked(evt);
            }
        });
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        btLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btLoginKeyPressed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        labelUENPflix.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        labelUENPflix.setForeground(new java.awt.Color(255, 0, 0));
        labelUENPflix.setText("UENPflix");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUENPflix, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(labelUENPflix, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(btSair))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelUsuario)
                    .addComponent(labelSenha)
                    .addComponent(inputUsuario)
                    .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(labelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSenha)
                .addGap(18, 18, 18)
                .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLogin)
                    .addComponent(btCadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btSair))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        String usuario = this.inputUsuario.getText();
        String senha = inputSenha.getText();
        boolean verifica = false;
        boolean cliente = false;
        boolean funcionario = false;
        
                    /*
            for (int i = 0; i<this.listaUsuario.size(); i++){
            //Login a = this.listaUsuario.get(i);
            Usuario a = this.listaUsuario.get(i);
            if(usuario.equalsIgnoreCase(a.getLogin()) && senha.equalsIgnoreCase(a.getSenha())){
            if(a.getCliente()==true){
            cliente = true;
            this.clientAtual = (Cliente)a;
            }
            if(a.getFuncionario()==true){
            funcionario = true;
            this.funcAtual = (Funcionario)a;
            }
            verifica = true;
            }
            }
            */
        try {
            int tipo = fc.getTipo(usuario, senha);
            switch (tipo) {
                case 1:
                    funcionario = true;
                    JOptionPane.showMessageDialog(null, "Login efetuado com sucesso !");
                    break;
                case 0:
                    cliente = true;
                    JOptionPane.showMessageDialog(null, "Login efetuado com sucesso !");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Login nao cadastrado");
                    break;
            }

        } catch (SQLException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(cliente==true){
            try {
                this.clientAtual = cc.getClient(usuario);
            } catch (SQLException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            TelaCliente telacliente = new TelaCliente(this.clientAtual);
            telacliente.setLocationRelativeTo(null);
            telacliente.setVisible(true);
        }
        if(funcionario==true){
            try {
                this.funcAtual = fc.getFunc(usuario);
            } catch (SQLException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            TelaFuncionario telafuncionario = new TelaFuncionario(this.funcAtual);
            telafuncionario.setLocationRelativeTo(null);
            telafuncionario.setVisible(true);
        }
    }//GEN-LAST:event_btLoginActionPerformed
     
    
    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        TelaCadastrar tela = new TelaCadastrar();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        Funcionario func = new Funcionario();
        func.setNome("Joao");
        func.setFuncionario();
        func.setGeneroFuncionario("Funcionario");
        Login a = new Login();
        a.setUsuario("joao");
        a.setSenha("123");
        func.setLogin(a);
        
        Cliente cli = new Cliente();
        Login b = new Login();
        cli.setNome("Cassia");
        cli.setIdade(18);
        cli.setEndereco("Jose Ferreira");
        cli.setCliente();
        cli.setGeneroFuncionario("Cliente");
        b.setUsuario("cassia");
        b.setSenha("123");
        cli.setLogin(b);
        this.listaUsuario.add(func);
        this.listaUsuario.add(cli);
        
        this.getContentPane().setBackground(Color.white);
    }//GEN-LAST:event_formWindowOpened

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btLoginMouseClicked

    private void inputSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSenhaActionPerformed

    private void login(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login
        // TODO add your handling code here:
    }//GEN-LAST:event_login

    private void btLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btLoginKeyPressed
        // TODO add your handling code here:
        String usuario = this.inputUsuario.getText();
        String senha = inputSenha.getText();
        boolean verifica = false;
        boolean cliente = false;
        boolean funcionario = false;
        
                    /*
            for (int i = 0; i<this.listaUsuario.size(); i++){
            //Login a = this.listaUsuario.get(i);
            Usuario a = this.listaUsuario.get(i);
            if(usuario.equalsIgnoreCase(a.getLogin()) && senha.equalsIgnoreCase(a.getSenha())){
            if(a.getCliente()==true){
            cliente = true;
            this.clientAtual = (Cliente)a;
            }
            if(a.getFuncionario()==true){
            funcionario = true;
            this.funcAtual = (Funcionario)a;
            }
            verifica = true;
            }
            }
            */
        try {
            int tipo = fc.getTipo(usuario, senha);
            switch (tipo) {
                case 1:
                    funcionario = true;
                    JOptionPane.showMessageDialog(null, "Login efetuado com sucesso !");
                    break;
                case 0:
                    cliente = true;
                    JOptionPane.showMessageDialog(null, "Login efetuado com sucesso !");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Login nao cadastrado");
                    break;
            }

        } catch (SQLException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(cliente==true){
            try {
                this.clientAtual = cc.getClient(usuario);
            } catch (SQLException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            TelaCliente telacliente = new TelaCliente(this.clientAtual);
            telacliente.setLocationRelativeTo(null);
            telacliente.setVisible(true);
        }
        if(funcionario==true){
            try {
                this.funcAtual = fc.getFunc(usuario);
            } catch (SQLException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            TelaFuncionario telafuncionario = new TelaFuncionario(this.funcAtual);
            telafuncionario.setLocationRelativeTo(null);
            telafuncionario.setVisible(true);
        }
    }//GEN-LAST:event_btLoginKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btSair;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUENPflix;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
