/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.FilmeController;
import filme.Filme;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static telas.TelaFuncionario.listaFilme;
/**
 *
 * @author jscal
 */
public class TelaFuncionario_TelaMenu_NovoFilme extends javax.swing.JFrame {
    private FilmeController fic = new FilmeController();
    /**
     * Creates new form TelaMenu_NovoFilme
     */
    public TelaFuncionario_TelaMenu_NovoFilme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputTitulo = new javax.swing.JTextField();
        inputDuracao = new javax.swing.JTextField();
        inputProdutora = new javax.swing.JTextField();
        inputElenco = new javax.swing.JTextField();
        labelGenero = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelDuracao = new javax.swing.JLabel();
        labelProdutora = new javax.swing.JLabel();
        labelElenco = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        inputGenero = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        labelUENPflix = new javax.swing.JLabel();
        labelCadastrarFilme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        inputElenco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputElencoActionPerformed(evt);
            }
        });

        labelGenero.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        labelGenero.setText("Genero:");

        labelTitulo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        labelTitulo.setText("Titulo:");

        labelDuracao.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        labelDuracao.setText("Duracao:");

        labelProdutora.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        labelProdutora.setText("Produtora:");

        labelElenco.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        labelElenco.setText("Elenco:");

        btCadastrar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btVoltar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        inputGenero.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        inputGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genero do Filme", "Romance", "Comedia", "Drama", "Terror", "Açao", "Aventura", "Suspense", "Ficção", "Documentario" }));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        labelUENPflix.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        labelUENPflix.setForeground(new java.awt.Color(255, 0, 0));
        labelUENPflix.setText("UENPflix");

        labelCadastrarFilme.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelCadastrarFilme.setForeground(new java.awt.Color(255, 0, 0));
        labelCadastrarFilme.setText("Cadastrar novo filme na plataforma");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelUENPflix)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCadastrarFilme)
                        .addGap(176, 176, 176))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelUENPflix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCadastrarFilme)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelElenco)
                            .addComponent(labelProdutora)
                            .addComponent(labelTitulo)
                            .addComponent(labelGenero)
                            .addComponent(labelDuracao))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputElenco, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadastrar)
                        .addGap(228, 228, 228))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelGenero)
                    .addComponent(inputGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(inputTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelElenco)
                    .addComponent(inputElenco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProdutora)
                    .addComponent(inputProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btVoltar))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputElencoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputElencoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputElencoActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        boolean confirma = false;
        
        Filme novoFilme = new Filme();
        
        novoFilme.setGenero(inputGenero.getSelectedItem().toString());
        novoFilme.setTitulo(inputTitulo.getText());
        novoFilme.setDuracao(inputDuracao.getText());
        novoFilme.setProdutora(inputProdutora.getText());
        novoFilme.setElenco(inputElenco.getText());
        
        try {
            fic.inserir(novoFilme);
            JOptionPane.showMessageDialog(null, "Filme cadastrado com sucesso!");
            confirma = true;
        } catch (SQLException ex) {
            Logger.getLogger(TelaFuncionario_TelaMenu_NovoFilme.class.getName()).log(Level.SEVERE, null, ex);
        }
        //listaFilme.add(novoFilme);
        
        if(confirma==true){
            this.setVisible(false);
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.white);
    }//GEN-LAST:event_formWindowGainedFocus

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario_TelaMenu_NovoFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario_TelaMenu_NovoFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario_TelaMenu_NovoFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario_TelaMenu_NovoFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario_TelaMenu_NovoFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField inputDuracao;
    private javax.swing.JTextField inputElenco;
    private javax.swing.JComboBox<String> inputGenero;
    private javax.swing.JTextField inputProdutora;
    private javax.swing.JTextField inputTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCadastrarFilme;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelElenco;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelProdutora;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUENPflix;
    // End of variables declaration//GEN-END:variables
}
