/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.FilmeController;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ramon
 */
public class TelaCliente_AvaliarFilme extends javax.swing.JFrame {
    private int avaliacao;
    private String titulo;
    private FilmeController fic = new FilmeController();
    private boolean avaliou = false;
    /**
     * Creates new form TelaCliente_AvaliarFilme
     */
    public TelaCliente_AvaliarFilme() {
        initComponents();
    }
    public TelaCliente_AvaliarFilme(String titulo) {
        this.titulo = titulo;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUENPflix = new javax.swing.JLabel();
        btPessimo = new javax.swing.JButton();
        btRegular = new javax.swing.JButton();
        btRuim = new javax.swing.JButton();
        btBom = new javax.swing.JButton();
        btExcelente = new javax.swing.JButton();
        labelUENPflix1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        labelUENPflix.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        labelUENPflix.setForeground(new java.awt.Color(255, 0, 0));
        labelUENPflix.setText("UENPflix");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        btPessimo.setText("1- Péssimo");
        btPessimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPessimoActionPerformed(evt);
            }
        });

        btRegular.setText("3- Regular");
        btRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegularActionPerformed(evt);
            }
        });

        btRuim.setText("2- Ruim");
        btRuim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRuimActionPerformed(evt);
            }
        });

        btBom.setText("4- Bom");
        btBom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBomActionPerformed(evt);
            }
        });

        btExcelente.setText("5- Excelente");
        btExcelente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcelenteActionPerformed(evt);
            }
        });

        labelUENPflix1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        labelUENPflix1.setForeground(new java.awt.Color(255, 0, 0));
        labelUENPflix1.setText("UENPflix");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Avalie o filme assistido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelUENPflix1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btPessimo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRuim, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcelente)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUENPflix1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBom)
                    .addComponent(btExcelente)
                    .addComponent(btRegular)
                    .addComponent(btRuim)
                    .addComponent(btPessimo))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBomActionPerformed
        this.avaliacao = 4;
        this.avaliou = true;
        
        if (this.avaliou){
            try {
                this.fic.avaliar(this.titulo, this.avaliacao);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente_AvaliarFilme.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                TelaFuncionario.listaFilme = fic.listar();
                JOptionPane.showMessageDialog(this, "Obrigado pela avaliação!");
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma nota antes!");
        }
    }//GEN-LAST:event_btBomActionPerformed

    private void btRuimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRuimActionPerformed
        this.avaliacao = 2;
        this.avaliou = true;
        
        if (this.avaliou){
            try {
                this.fic.avaliar(this.titulo, this.avaliacao);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente_AvaliarFilme.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                TelaFuncionario.listaFilme = fic.listar();
                JOptionPane.showMessageDialog(this, "Obrigado pela avaliação!");
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma nota antes!");
        }
    }//GEN-LAST:event_btRuimActionPerformed

    private void btPessimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPessimoActionPerformed
        this.avaliacao = 1;
        this.avaliou = true;
        
        if (this.avaliou){
            try {
                this.fic.avaliar(this.titulo, this.avaliacao);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente_AvaliarFilme.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                TelaFuncionario.listaFilme = fic.listar();
                JOptionPane.showMessageDialog(this, "Obrigado pela avaliação!");
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma nota antes!");
        }
    }//GEN-LAST:event_btPessimoActionPerformed

    private void btExcelenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcelenteActionPerformed
        this.avaliacao = 5;
        this.avaliou = true;
        
        if (this.avaliou){
            try {
                this.fic.avaliar(this.titulo, this.avaliacao);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente_AvaliarFilme.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                TelaFuncionario.listaFilme = fic.listar();
                JOptionPane.showMessageDialog(this, "Obrigado pela avaliação!");
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma nota antes!");
        }
    }//GEN-LAST:event_btExcelenteActionPerformed

    private void btRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegularActionPerformed
        this.avaliacao = 3;
        this.avaliou = true;
        
        if (this.avaliou){
            try {
                this.fic.avaliar(this.titulo, this.avaliacao);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente_AvaliarFilme.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                TelaFuncionario.listaFilme = fic.listar();
                JOptionPane.showMessageDialog(this, "Obrigado pela avaliação!");
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma nota antes!");
        }
    }//GEN-LAST:event_btRegularActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.black);
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_AvaliarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_AvaliarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_AvaliarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_AvaliarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente_AvaliarFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBom;
    private javax.swing.JButton btExcelente;
    private javax.swing.JButton btPessimo;
    private javax.swing.JButton btRegular;
    private javax.swing.JButton btRuim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelUENPflix;
    private javax.swing.JLabel labelUENPflix1;
    // End of variables declaration//GEN-END:variables
}
