/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import filme.Filme;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import banco.FilmeController;
import banco.FuncionarioController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import static telas.TelaLogin.listaUsuario;
import usuario.funcionario.Funcionario;

/**
 *
 * @author jscal
 */
public class TelaFuncionario extends javax.swing.JFrame {
    private FilmeController fic = new FilmeController();
    public static ArrayList<Filme> listaFilme = new ArrayList<>();
    String colunas[] = {"Genero", "Titulo", "Duracao", "Produtora", "Elenco"};
    private int rowDelete;
    private String codFuncSelecionado;
    private Funcionario funcionarioAtual;
    private FuncionarioController fc = new FuncionarioController();
    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
    }
    
    public TelaFuncionario(Funcionario funcionario){
        initComponents();
        try {
            TelaFuncionario.listaFilme = fic.listar();
        } catch (SQLException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.funcionarioAtual = funcionario;
        btExcluir.setEnabled(false);
        btEditar.setEnabled(false);
    }
    
    public void criarTabela(){
    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("Genero");
    modelo.addColumn("Titulo");
    modelo.addColumn("Duracao");
    modelo.addColumn("Produtora");
    modelo.addColumn("Elenco");
    modelo.addColumn("Visualizacoes");
    modelo.addColumn("Avaliação Média");
    
    
    for (Filme a : this.listaFilme) {
            modelo.addRow(new Object[]{
                a.getGenero(), a.getTitulo(), a.getDuracao(), a.getProdutora(), a.getElenco(), a.getAssistido(), a.getPontuacao()
            });
        }
    
        tabelaFilmes.setModel(modelo);
        tabelaFilmes.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        @Override
        public void valueChanged(ListSelectionEvent e) {
        int linha = tabelaFilmes.getSelectedRow();
                if (linha != -1) {
                    rowDelete = linha;
                    codFuncSelecionado
                            = (String) tabelaFilmes.getValueAt(linha, 1);
                    /*   A variavel codFuncSelecionado armazenao 
                     * o conteudo referente a coluna determina, 
                     * no caso a coluna determina é a 1, que é
                     * a coluna referente aos TITULOS dos filmes
                     */
                    btExcluir.setEnabled(true);
                    btEditar.setEnabled(true);
                } else {
                    btExcluir.setEnabled(false);
                    btEditar.setEnabled(false);
                }
        }    
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFilmes = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelBemVindo = new javax.swing.JLabel();
        labelUENPflix = new javax.swing.JLabel();
        btBusca = new javax.swing.JButton();
        inputBusca = new javax.swing.JTextField();
        labelBuscarFilme = new javax.swing.JLabel();
        btAtualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        BarraMenu_Perfil = new javax.swing.JMenu();
        BarraMenu_Perfil_AlterarCadastro = new javax.swing.JMenuItem();
        BarraMenu_Perfil_Sair = new javax.swing.JMenuItem();
        BarraMenu_Filmes = new javax.swing.JMenu();
        BarraMenu_Filmes_NovoFilme = new javax.swing.JMenuItem();
        BarraMenu_Clientes = new javax.swing.JMenu();
        BarraMenu_Clientes_GerenciarClientes = new javax.swing.JMenuItem();
        BarraMenu_Clientes_GerenciarHistorico = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        tabelaFilmes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tabelaFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaFilmes);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        labelBemVindo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        labelBemVindo.setForeground(new java.awt.Color(255, 255, 255));
        labelBemVindo.setText("Bem - Vindo à equipe  ");

        labelUENPflix.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        labelUENPflix.setForeground(new java.awt.Color(255, 0, 0));
        labelUENPflix.setText("UENPflix");

        btBusca.setText("Buscar");
        btBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaActionPerformed(evt);
            }
        });

        labelBuscarFilme.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        labelBuscarFilme.setForeground(new java.awt.Color(240, 240, 240));
        labelBuscarFilme.setText("Buscar filme: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(640, 640, 640)
                        .addComponent(labelBuscarFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBusca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(labelBemVindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUENPflix)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btBusca)
                            .addComponent(inputBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBuscarFilme))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelUENPflix)
                            .addComponent(labelBemVindo))
                        .addGap(37, 37, 37))))
        );

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        BarraMenu_Perfil.setText("Perfil");

        BarraMenu_Perfil_AlterarCadastro.setText("Alterar Cadastro");
        BarraMenu_Perfil_AlterarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraMenu_Perfil_AlterarCadastroActionPerformed(evt);
            }
        });
        BarraMenu_Perfil.add(BarraMenu_Perfil_AlterarCadastro);

        BarraMenu_Perfil_Sair.setText("Sair");
        BarraMenu_Perfil_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraMenu_Perfil_SairActionPerformed(evt);
            }
        });
        BarraMenu_Perfil.add(BarraMenu_Perfil_Sair);

        jMenuBar1.add(BarraMenu_Perfil);

        BarraMenu_Filmes.setText("Filmes");

        BarraMenu_Filmes_NovoFilme.setText("Novo filme");
        BarraMenu_Filmes_NovoFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraMenu_Filmes_NovoFilmeActionPerformed(evt);
            }
        });
        BarraMenu_Filmes.add(BarraMenu_Filmes_NovoFilme);

        jMenuBar1.add(BarraMenu_Filmes);

        BarraMenu_Clientes.setText("Clientes");

        BarraMenu_Clientes_GerenciarClientes.setText("Gerenciar Clientes");
        BarraMenu_Clientes_GerenciarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraMenu_Clientes_GerenciarClientesActionPerformed(evt);
            }
        });
        BarraMenu_Clientes.add(BarraMenu_Clientes_GerenciarClientes);

        BarraMenu_Clientes_GerenciarHistorico.setText("Gerenciar Historico");
        BarraMenu_Clientes_GerenciarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraMenu_Clientes_GerenciarHistoricoActionPerformed(evt);
            }
        });
        BarraMenu_Clientes.add(BarraMenu_Clientes_GerenciarHistorico);

        jMenuBar1.add(BarraMenu_Clientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraMenu_Perfil_AlterarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraMenu_Perfil_AlterarCadastroActionPerformed
        // TODO add your handling code here:
        TelaFuncionario_TelaMenu_AlterarCadastroFuncionario telaAltFunc = new TelaFuncionario_TelaMenu_AlterarCadastroFuncionario(this.funcionarioAtual);
        telaAltFunc.setLocationRelativeTo(null);
        telaAltFunc.setVisible(true);
    }//GEN-LAST:event_BarraMenu_Perfil_AlterarCadastroActionPerformed

    private void BarraMenu_Filmes_NovoFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraMenu_Filmes_NovoFilmeActionPerformed
        // TODO add your handling code here:
        TelaFuncionario_TelaMenu_NovoFilme telaNovoFilme = new TelaFuncionario_TelaMenu_NovoFilme();
        telaNovoFilme.setLocationRelativeTo(null);
        telaNovoFilme.setVisible(true);
    }//GEN-LAST:event_BarraMenu_Filmes_NovoFilmeActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.white);
        criarTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        Filme filme= null;
        /*
        for (Filme f : this.listaFilme) {
            if (f.getTitulo().equals(codFuncSelecionado)) {
                filme = f;
            }
        }
        */
        
        int op = JOptionPane.showConfirmDialog(this,
                "Deseja excluir o: " + this.codFuncSelecionado + " ?");

        if (op == 0) {
            try {
                fic.excluir(codFuncSelecionado);
            } catch (SQLException ex) {
                Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
            //this.listaFilme.remove(filme);
            btExcluir.setEnabled(false);
        }
        
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        Filme filme = null;
        for (Filme f : this.listaFilme) {
            if (f.getTitulo().equals(codFuncSelecionado)) {
                filme = f;
            }
        }
        TelaFuncionario_Tela_Editar_Filme telaEditar = new TelaFuncionario_Tela_Editar_Filme(filme);
        telaEditar.setLocationRelativeTo(null);
        telaEditar.setVisible(true);
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void BarraMenu_Perfil_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraMenu_Perfil_SairActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
//        TelaLogin telaLogin = new TelaLogin();
//        telaLogin.setLocationRelativeTo(null);
//        telaLogin.setVisible(true);
    }//GEN-LAST:event_BarraMenu_Perfil_SairActionPerformed

    private void BarraMenu_Clientes_GerenciarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraMenu_Clientes_GerenciarClientesActionPerformed
        // TODO add your handling code here:
        TelaFuncionario_TelaMenu_GerenciarCliente telaGerenciarCliente = new TelaFuncionario_TelaMenu_GerenciarCliente();
        try {
            TelaLogin.listaUsuario = fc.listarTodos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaFuncionario_TelaMenu_GerenciarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        telaGerenciarCliente.setLocationRelativeTo(null);
        telaGerenciarCliente.setVisible(true);
    }//GEN-LAST:event_BarraMenu_Clientes_GerenciarClientesActionPerformed

    private void btBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaActionPerformed
        // TODO add your handling code here:
        boolean existe = false;
        String nomeBuscado = inputBusca.getText();
        Filme filme = null;
        
        for (Filme f : this.listaFilme) {
            if (f.getTitulo().equalsIgnoreCase(nomeBuscado)) {
                existe = true;
                filme = f;
            }
        }
        
        if(existe){
            TelaFuncionario_Tela_Editar_Filme telaEditar = new TelaFuncionario_Tela_Editar_Filme(filme);
            telaEditar.setLocationRelativeTo(null);
            telaEditar.setVisible(true);
        }
        if(existe==false){
            JOptionPane.showMessageDialog(null, "Filme não encontrado !");
        }
    }//GEN-LAST:event_btBuscaActionPerformed

    private void BarraMenu_Clientes_GerenciarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraMenu_Clientes_GerenciarHistoricoActionPerformed
        // TODO add your handling code here:
        TelaFuncionario_TelaMenu_GerenciarHistorico telaHistorico = new TelaFuncionario_TelaMenu_GerenciarHistorico();
        telaHistorico.setLocationRelativeTo(null);
        telaHistorico.setVisible(true);
    }//GEN-LAST:event_BarraMenu_Clientes_GerenciarHistoricoActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        try {
            TelaFuncionario.listaFilme = fic.listar();
            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BarraMenu_Clientes;
    private javax.swing.JMenuItem BarraMenu_Clientes_GerenciarClientes;
    private javax.swing.JMenuItem BarraMenu_Clientes_GerenciarHistorico;
    private javax.swing.JMenu BarraMenu_Filmes;
    private javax.swing.JMenuItem BarraMenu_Filmes_NovoFilme;
    private javax.swing.JMenu BarraMenu_Perfil;
    private javax.swing.JMenuItem BarraMenu_Perfil_AlterarCadastro;
    private javax.swing.JMenuItem BarraMenu_Perfil_Sair;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBusca;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JTextField inputBusca;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBemVindo;
    private javax.swing.JLabel labelBuscarFilme;
    private javax.swing.JLabel labelUENPflix;
    private javax.swing.JTable tabelaFilmes;
    // End of variables declaration//GEN-END:variables
}
