/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.ClienteController;
import banco.FilmeController;
import filme.Filme;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
//import static telas.TelaCliente.listaFavoritos;
import static telas.TelaCliente.listaHistorico;
import usuario.cliente.Cliente;
import usuario.cliente.Favoritos;
import usuario.cliente.HistoricoCliente;

/**
 *
 * @author jscal
 */
public class TelaCliente_TelaMenu_Favoritos extends javax.swing.JFrame {
    String colunas[] = {"Genero", "Titulo", "Duracao", "Produtora", "Elenco"};
    private int rowDelete;
    private String codFuncSelecionado;
    private Cliente cliente;
    private ArrayList<Filme> favs = new ArrayList();
    private ClienteController cc = new ClienteController();
    private FilmeController fic = new FilmeController();
    /**
     * Creates new form TelaMenu_Favoritos
     */
    public TelaCliente_TelaMenu_Favoritos() {
        initComponents();
    }
    
    public TelaCliente_TelaMenu_Favoritos(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        try {
            this.favs = cc.filmesFavoritos(this.cliente.getLogin());
        } catch (SQLException ex) {
            Logger.getLogger(TelaCliente_TelaMenu_Favoritos.class.getName()).log(Level.SEVERE, null, ex);
        }
        btAssistir.setEnabled(false);
        btRemover.setEnabled(false);
    }
    
    public void criarTabela(){
    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("Genero");
    modelo.addColumn("Titulo");
    modelo.addColumn("Duracao");
    modelo.addColumn("Produtora");
    modelo.addColumn("Elenco");
    modelo.addColumn("Avaliação");
    
    
    
    for (Filme a : this.favs) {
            modelo.addRow(new Object[]{
                a.getGenero(), a.getTitulo(), a.getDuracao(), a.getProdutora(), a.getElenco(), a.getPontuacao()
            });
        }
    
        tabelaFavoritos.setModel(modelo);
        tabelaFavoritos.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        @Override
        public void valueChanged(ListSelectionEvent e) {
        int linha = tabelaFavoritos.getSelectedRow();
                if (linha != -1) {
                    rowDelete = linha;
                    codFuncSelecionado
                            = (String) tabelaFavoritos.getValueAt(linha, 1);
                    /*   A variavel codFuncSelecionado armazenao 
                     * o conteudo referente a coluna determina, 
                     * no caso a coluna determina é a 1, que é
                     * a coluna referente aos TITULOS dos filmes
                     */
                    btAssistir.setEnabled(true);
                    btRemover.setEnabled(true);
                } else {
                    btAssistir.setEnabled(false);
                    btRemover.setEnabled(false);
                }
        }    
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFavoritos = new javax.swing.JTable();
        btRemover = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btAtualizar = new javax.swing.JButton();
        btAssistir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        tabelaFavoritos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaFavoritos);

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("FAVORITOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btAssistir.setText("Assistir");
        btAssistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAssistirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(btVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAssistir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAssistir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        // TODO add your handling code here:
        /*
        Filme filme= null;
        for (Filme f : this.favs) {
            if (f.getTitulo().equals(codFuncSelecionado)) {
                filme = f;
            }
        }
        */
        int op = JOptionPane.showConfirmDialog(this,
                "Deseja excluir " + codFuncSelecionado + " dos seus favoritos?");

        if (op == 0) {
            try {
                cc.delFav(this.cliente.getLogin(), codFuncSelecionado);
                JOptionPane.showMessageDialog(this, "Filme removido dos seus favoritos!");
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente_TelaMenu_Favoritos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            HistoricoCliente historico = new HistoricoCliente();
            historico.setFilmeAssistidos(codFuncSelecionado);
            historico.setMovimentacao("Removido Favoritos");
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm");
            String horario = String.valueOf(sdf.format(new Date()));
            historico.setHorario(horario);
            
            listaHistorico.add(historico);
            btRemover.setEnabled(false);
        }
        
    }//GEN-LAST:event_btRemoverActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.white);
        criarTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        try {
            this.favs = cc.filmesFavoritos(this.cliente.getLogin());
            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(TelaCliente_TelaMenu_Favoritos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btAssistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAssistirActionPerformed
        HistoricoCliente historico = new HistoricoCliente();
        int op = JOptionPane.showConfirmDialog(this, "Desejar assistir: \n" + codFuncSelecionado +
                "?");

        if (op == 0) {
            JOptionPane.showMessageDialog(null, "ASSISTINDO\n" + codFuncSelecionado);
            
            historico.setFilmeAssistidos(codFuncSelecionado);
            historico.setMovimentacao("Assistido");
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
            String horario = String.valueOf(sdf.format(new Date()));
            historico.setHorario(horario);
            
            try {
                cc.addHist(this.cliente.getLogin(), historico);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            TelaCliente_AvaliarFilme telaAvaliar = new TelaCliente_AvaliarFilme(codFuncSelecionado);
            telaAvaliar.setLocationRelativeTo(null);
            telaAvaliar.setVisible(true);
        }
        try {//adiciona um ao contador de vezes que o filme foi assistido
            fic.assistirFilme(codFuncSelecionado);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAssistirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_TelaMenu_Favoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_TelaMenu_Favoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_TelaMenu_Favoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente_TelaMenu_Favoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente_TelaMenu_Favoritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAssistir;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaFavoritos;
    // End of variables declaration//GEN-END:variables
}
